name: "Checking app: testing and linting JS"

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'package.json'
      - 'package.lock'

jobs:
  test-and-lint-js:
    name: Test & lint JS codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0 # https://github.com/actions/checkout

      - name: Cache dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4 # https://github.com/actions/cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package.lock') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0 # https://github.com/actions/setup-node
        with:
          node-version: 22.20.0

      - name: Instal npm dependencies
        run: npm clean-install

      - name: Run JS linter
        run: npm run lint
